version: '3.3'

services:
    frontend:
        build:
            context: ./frontend
            args:
                - REACT_APP_BACKEND_PORT=${BACKEND_PORT}
                - REACT_APP_BACKEND_HOSTNAME=${BACKEND_HOSTNAME}
                - REACT_APP_BACKEND_PROTOCOL=${BACKEND_PROTOCOL}
        ports:
            - ${FRONTEND_PORT}:80
        depends_on:
            - backend
        networks:
            - thesis

    backend:
        build:
            context: ./backend
        ports:
            - ${BACKEND_PORT}:3000
        environment:
            - APP_MODE=${APP_MODE}
            - APP_LOGS_EXPANDED=${APP_LOGS_EXPANDED}
            - APP_JWT_KEY=${APP_JWT_KEY}

            - MONGO_PROTOCOL=${MONGO_PROTOCOL}
            - MONGO_HOSTNAME=${MONGO_HOSTNAME}
            - MONGO_PORT=${MONGO_PORT}
            - MONGO_DATABASE=${MONGO_DATABASE}
            - MONGO_USERNAME=${MONGO_USERNAME}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MONGO_ARGUMENTS=${MONGO_ARGUMENTS}
        networks:
            - thesis

networks:
    thesis:
        driver: bridge
