FROM node:16-alpine AS builder

WORKDIR /app

COPY ./package*.json ./
RUN npm install

COPY ./tsconfig.json ./tsconfig.json
COPY ./src ./src
RUN npm run build


FROM node:16-alpine AS server

WORKDIR /app

COPY package* ./
RUN npm install --production

COPY --from=builder /app/build ./build

CMD npm run start
